query album($id: ID!) {
    album(id: $id) {
        actions {
            add
            delete
            edit
        }
        date
        description {
            locale
            text
        }
        id
        submitter {
            userId
            username
            avatar {
              size
              width
              height
              type
              url
            }
        }
        title {
            locale
            text
        }
    }
}
