query album($id: ID!) {
    album(id: $id) {
        actions {
            add
            delete
            edit
        }
        description
        id
        submitter {
            userId
            username
            avatar {
              size
              width
              height
              type
              url
            }
        }
        title
    }
}
