query album($id: ID!) {
    album(id: $id) {
        id
        title
        description
        media {
            id
            title
            mediaType
            thumbs {
                type
                size
                url
                height
                width
            }
            images {
                type
                size
                url
                height
                width
            }
        }
    }
}
