query album($id: ID!) {
    album(id: $id, itemCount: 75) {
        actions {
            add
            delete
            edit
        }
        description
        id
        media {
            id
            title
            mediaType
            thumbs {
                type
                size
                url
                height
                width
            }
            images {
                type
                size
                url
                height
                width
            }
        }
        submitter {
            userId
            username
            avatar {
              size
              width
              height
              type
              url
            }
        }
        title
    }
}
