query comment($id: ID!) {
    comment(id: $id) {
        actions {
            delete
            edit
        }
        id
        content {
            locale
            original
            text
        }
        date
        parentId
        parentType
        submitter {
            userId
            username
            avatar {
                size
                width
                height
                type
                url
            }
        }
        tone
    }
}