query fourDown($id: ID!, $countItems: Int, $startItem: Int, $surveyId: ID!) {
    album(id: $id) {
        actions {
            add
            delete
            edit
        }
        albumContributions
        albumVisibility
        date
        description {
            locale
            original
            text
        }
        id
        submitter {
            userId
            username
            avatar {
              size
              width
              height
              type
              url
            }
        }
        title {
            locale
            original
            text
        }
    }
    getSurveyVote(surveyId: $surveyId) {
        surveyId
        choice
    }
    listMedia(albumId: $id, countItems: $countItems, startItem: $startItem) {
        actions {
            delete
            edit
        }
        id
        date
        description {
            locale
            original
            text
        }
        mediaType
        mediaSubType
        embedUrl
        vendorKey
        vendorUrl
        height
        width
        thumbHeight
        thumbWidth
        title {
            locale
            original
            text
        }
        thumbs {
            type
            size
            url
            height
            width
        }
        images {
            type
            size
            url
            height
            width
        }
        reactions {
          count
          userReactionId
          type
        }
        submitter {
            userId
            username
            avatar {
              size
              width
              height
              type
              url
            }
        }
    }
}
