query photo($id: ID!) {
    listComments(parentType: "photo", parentId: $id) {
        id
        content
        date
        submitter {
            userId
            username
            avatar {
                size
                width
                height
                type
                url
            }
        }
        tone
    }
}
