query home($galleryAlbumId: ID!) {
    album(id: $galleryAlbumId) {
        actions {
            add
            delete
            edit
        }
        albumContributions
        albumVisibility
        description
        id
        media {
            id
            mediaType
            title
            thumbs {
                type
                size
                url
                height
                width
            }
        }
        title
    }
    listAlbums {
        actions {
            add
            delete
            edit
        }
        albumContributions
        albumVisibility
        description
        id
        media {
            id
            mediaType
            title
            thumbs {
                type
                size
                url
                height
                width
            }
        }
        submitter {
            userId
            username
            avatar {
              size
              width
              height
              type
              url
            }
        }
        title
    }
}