query home($galleryAlbumId: ID!) {
    album(id: $galleryAlbumId) {
        id
        title
        description
        media {
            id
            mediaType
            title
            thumbs {
                type
                size
                url
                height
                width
            }
        }
    }
    listAlbums {
        id
        title
        description
        media {
            id
            mediaType
            title
            thumbs {
                type
                size
                url
                height
                width
            }
        }
    }
}