query homePage {
    spotlight(limit: 3) {
        id
        name
        Video {
            id
            name
            poster
        }
    }
    fixtures(limit: 8) {
        id
        location
        startDate
        getLiveStatus
        stats {
            homeTeam {
                team {
                    id
                    name
                    shortName
                    picture
                }
            }
            awayTeam {
                team {
                    id
                    name
                    shortName
                    picture
                }
            }
        }
    }
    results(limit: 3) {
        id
        location
        startDate
        getLiveStatus
        stats {
            homeTeam {
                team {
                    id
                    name
                    shortName
                    picture
                }
                goals
            }
            awayTeam {
                team {
                    id
                    name
                    shortName
                    picture
                }
                goals
            }
        }
    }
    latestVideos {
        id
        name
        description
        url
        poster
        like
        bookmark
        Event {
            id
            name
        }
    }
    allVideos {
        ... on Videos {
            items {
                id
                poster
                name
                like
                bookmark
                watchCount
                Event {
                    id
                    name
                }
            }
        }
    }
    allTeams {
        ... on Teams {
            items {
                id
                jerseyPicture
                picture
                name
                like
                bookmark
                watchCount
            }
        }
    }
    standings {
          team {
            id
            name
            picture
            jerseyPicture
          }
          position
          played
          won
          drawn
          lost
          goalsFor
          goalsAgainst
          goalsDifference
          points
          form
        }
}
