query home($galleryAlbumId: ID!, $count: Int!, $countItems: Int!, $skipAlbums: [String]) {
    album(id: $galleryAlbumId, countItems: $countItems) {
        actions {
            add
            delete
            edit
        }
        albumContributions
        albumVisibility
        date
        description {
            locale
            original
            text
        }
        id
        itemCount
        media {
            actions {
                delete
                edit
            }
            id
            date
            description {
                locale
                original
                text
            }
            mediaType
            mediaSubType
            embedUrl
            height
            width
            title {
                locale
                original
                text
            }
            thumbs {
                type
                size
                url
                height
                width
            }
            images {
                type
                size
                url
                height
                width
            }
            submitter {
                userId
                username
                avatar {
                  size
                  width
                  height
                  type
                  url
                }
            }
        }
        title {
            locale
            original
            text
        }
    }
    listAlbums(count: $count, countItems: $countItems, skipAlbums: $skipAlbums) {
        actions {
            add
            delete
            edit
        }
        albumContributions
        albumVisibility
        date
        description {
            locale
            original
            text
        }
        id
        itemCount
        media {
            actions {
                delete
                edit
            }
            id
            date
            description {
                locale
                original
                text
            }
            mediaType
            mediaSubType
            embedUrl
            height
            width
            title {
                locale
                original
                text
            }
            thumbs {
                type
                size
                url
                height
                width
            }
            images {
                type
                size
                url
                height
                width
            }
            submitter {
                userId
                username
                avatar {
                  size
                  width
                  height
                  type
                  url
                }
            }
        }
        submitter {
            userId
            username
            avatar {
              size
              width
              height
              type
              url
            }
        }
        title {
            locale
            original
            text
        }
    }
}