query listComments($parentType: String!, $parentId: ID!) {
    listComments(parentType: $parentType, parentId: $parentId) {
        actions {
            delete
            edit
        }
        id
        content {
            locale
            original
            text
        }
        date
        reactions{
          count
          userReactionId
          type
        }
        submitter {
            userId
            username
            avatar {
                size
                width
                height
                type
                url
            }
        }
        tone
    }
}