query listUsers {
    listUsers {
        avatar {
          size
          width
          height
          type
          url
        }
        bio {
            locale
            text
        }
        cover {
          size
          width
          height
          type
          url
        }
        userId
        username
    }
}