query listMedia($albumId: ID!, $countItems: Int, $startItem: Int) {
    listMedia(albumId: $albumId, countItems: $countItems, startItem: $startItem) {
        actions {
            delete
            edit
        }
        id
        date
        description {
            locale
            text
        }
        mediaType
        mediaSubType
        embedUrl
        height
        images {
            type
            size
            url
            height
            width
        }
        width
        title {
            locale
            text
        }
        thumbs {
            type
            size
            url
            height
            width
        }
        submitter {
            userId
            username
            avatar {
              size
              width
              height
              type
              url
            }
        }
    }
}
