query listAlbums($count: Int!, $countItems: Int!) {
    listAlbums(count: $count, countItems: $countItems) {
        actions {
            add
            delete
            edit
        }
        description
        id
        itemCount
        media {
            id
            mediaType
            title
            thumbs {
                type
                size
                url
                height
                width
            }
        }
        submitter {
            userId
            username
            avatar {
              size
              width
              height
              type
              url
            }
        }
        title
    }
}
