query listAlbums {
    listAlbums {
        id
        title
        description
        media {
            id
            mediaType
            thumbs {
                type
                size
                url
                height
                width
            }
        }
    }
}
