query listAlbums {
    listAlbums {
        id
        title
        description
        actions {
            add
            delete
            edit
        }
        media {
            id
            mediaType
            thumbs {
                type
                size
                url
                height
                width
            }
        }
    }
}
