query listAlbums($count: Int!, $start: Int, $countItems: Int!, $skipAlbums: [String]) {
    listAlbums(count: $count, start: $start, countItems: $countItems, skipAlbums: $skipAlbums) {
        actions {
            add
            delete
            edit
        }
        description
        id
        itemCount
        media {
            id
            mediaType
            title
            thumbs {
                type
                size
                url
                height
                width
            }
        }
        submitter {
            userId
            username
            avatar {
              size
              width
              height
              type
              url
            }
        }
        title
    }
}
