query {
  me {
    avatar {
      size
      width
      height
      type
      url
    }
    cover {
      size
      width
      height
      type
      url
    }
    email
    firstName
    lang
    status
    userId
    username
  }
}
