query {
  me {
    avatar {
      size
      width
      height
      type
      url
    }
    bio {
        locale
        text
    }
    cover {
      size
      width
      height
      type
      url
    }
    email
    firstName
    locale
    status
    timezone
    userId
    username
  }
}
