query media($id: ID!) {
    media(id: $id) {
        actions {
            delete
            edit
        }
        date
        description {
            locale
            original
            text
        }
        embedUrl
        height
        id
        images {
          type
          size
          url
          height
          width
        }
        mediaType
        mediaSubType
        thumbHeight
        thumbWidth
        title {
            locale
            original
            text
        }
        vendorKey
        vendorUrl
        width
        thumbs {
          type
          size
          url
          height
          width
        }
        album {
            id
            title {
                locale
                original
                text
            }
        }
        reactions {
          count
          userReactionId
          type
        }
        submitter {
            userId
            username
            avatar {
              size
              width
              height
              type
              url
            }
        }
    }
}
