query media($id: ID!, $mediaType: String!) {
    media(id: $id) {
        date
        description {
            locale
            text
        }
        embedUrl
        height
        id
        images {
          type
          size
          url
          height
          width
        }
        mediaType
        mediaSubType
        title {
            locale
            text
        }
        vendorUrl
        width
        thumbs {
          type
          size
          url
          height
          width
        }
        album {
            id
            title {
                locale
                text
            }
        }
        submitter {
            userId
            username
            avatar {
              size
              width
              height
              type
              url
            }
        }
    }
    listComments(parentType: $mediaType, parentId: $id) {
        actions {
            delete
            edit
        }
        id
        content {
            locale
            text
        }
        date
        submitter {
            userId
            username
            avatar {
                size
                width
                height
                type
                url
            }
        }
        tone
    }
}
