query photo($id: ID!) {
    photo(id: $id) {
        id
        title
        description
        images {
          type
          size
          url
        }
        thumbs {
          type
          size
          url
        }
        album {
            id
            title
        }
        submitter {
            userId
            username
        }
    }
}
