query photo($id: ID!) {
    photo(id: $id) {
        id
        title
        description
        images {
          type
          size
          url
          height
          width
        }
        thumbs {
          type
          size
          url
        }
        album {
            id
            title
        }
        submitter {
            userId
            username
        }
    }
    listComments(parentType: "photo", parentId: $id) {
        id
        content
        date
        submitter {
            userId
            username
            avatar {
                size
                width
                height
                type
                url
            }
        }
        tone
    }
}
