query userProfile($userId: ID!) {
    user(userId: $userId) {
        userId
        username
        firstName
        bio
        album{
          id
          title
          media {
            images {
                size
                width
                height
                type
                url
            }
          }
        }
        avatar {
          size
          width
          height
          type
          url
        }
        cover {
          size
          width
          height
          type
          url
        }
    }
    listAlbums(userId: $userId) {
        id
        title
        description
        media {
            id
            title
            mediaType
            thumbs {
                type
                size
                url
                height
                width
            }
            images {
                type
                size
                url
                height
                width
            }
        }
    }
}
