query userProfile($userId: ID!) {
    user(userId: $userId) {
        userId
        username
        firstName
        bio
        album {
          id
          title
          media {
            images {
                size
                width
                height
                type
                url
            }
          }
        }
        avatar {
          size
          width
          height
          type
          url
        }
        cover {
          size
          width
          height
          type
          url
        }
    }
    listAlbums(userId: $userId) {
        actions {
            add
            delete
            edit
        }
        albumContributions
        albumVisibility
        description
        id
        itemCount
        media {
            id
            title
            mediaType
            thumbs {
                type
                size
                url
                height
                width
            }
            images {
                type
                size
                url
                height
                width
            }
        }
        title
    }
}
