query userProfile($userId: ID!) {
    user(userId: $userId) {
        userId
        username
        firstName
        bio {
            locale
            text
        }
        album {
          id
          title {
            locale
            text
          }
          media {
            actions {
                delete
                edit
            }
            images {
                size
                width
                height
                type
                url
            }
          }
        }
        avatar {
          size
          width
          height
          type
          url
        }
        cover {
          size
          width
          height
          type
          url
        }
    }
    listAlbums(userId: $userId) {
        actions {
            add
            delete
            edit
        }
        albumContributions
        albumVisibility
        description {
            locale
            text
        }
        id
        itemCount
        media {
            actions {
                delete
                edit
            }
            date
            description {
                locale
                text
            }
            id
            images {
                type
                size
                url
                height
                width
            }
            thumbs {
                type
                size
                url
                height
                width
            }
            title {
                locale
                text
            }
            mediaType
            submitter {
                userId
                username
                avatar {
                  size
                  width
                  height
                  type
                  url
                }
            }
        }
        title {
            locale
            text
        }
    }
}
