query video($id: ID!) {
    video(id: $id) {
        id
        title
        description
        mediaSubType
        thumbs {
          type
          size
          url
          height
          width
        }
        embedUrl
        vendorUrl
        album {
            id
            title
        }
        submitter {
            userId
            username
        }
    }
}
