query video($id: ID!) {
    video(id: $id) {
        description
        embedUrl
        height
        id
        mediaSubType
        title
        vendorUrl
        width
        thumbs {
          type
          size
          url
          height
          width
        }
        album {
            id
            title
        }
        submitter {
            userId
            username
        }
    }
    listComments(parentType: "video", parentId: $id) {
        id
        content
        date
        submitter {
            userId
            username
            avatar {
                size
                width
                height
                type
                url
            }
        }
        tone
    }

}
