const STEP_START = 0;
const STEP_OAUTH_FETCHING_TOKEN = 'STEP_OAUTH_FETCHING_TOKEN';
const STEP_OAUTH_CHECKING_EMAIL = 'STEP_OAUTH_CHECKING_EMAIL';
const STEP_ENTERING_USERNAME = 'STEP_ENTERING_USERNAME';
const STEP_CREATING_PROFILE = 'STEP_CREATING_PROFILE';
const STEP_SIGN_IN_IN_PROGRESS = 'STEP_SIGN_IN_IN_PROGRESS';
const STEP_SIGN_IN_SUCCESS = 'STEP_SIGN_IN_SUCCESS';

const STEP_OAUTH_NO_DATA_ERROR = 'err1';
const STEP_OAUTH_NO_USER = 'err2';
const STEP_EXISTING_USERNAME_ERROR = 'err3';
const STEP_PROFILE_CREATION_ERROR = 'err4';
const STEP_SIGN_IN_ERROR = 'err5';

const steps = {
  STEP_START,
  STEP_OAUTH_FETCHING_TOKEN,
  STEP_OAUTH_CHECKING_EMAIL,
  STEP_ENTERING_USERNAME,
  STEP_CREATING_PROFILE,
  STEP_SIGN_IN_IN_PROGRESS,
  STEP_SIGN_IN_SUCCESS,

  STEP_OAUTH_NO_DATA_ERROR,
  STEP_OAUTH_NO_USER,
  STEP_EXISTING_USERNAME_ERROR,
  STEP_PROFILE_CREATION_ERROR,
  STEP_SIGN_IN_ERROR,
};

export default steps;
