const routes = {
  ABOUT: '/about',
  ALBUM: '/album/:id',
  ALBUM_NEW: '/new-album',
  ALBUMS: '/albums',
  CONTACT: '/contact',
  CONFIRM_EMAIL: '/confirm-email',
  ERROR: '/error/:id/:message',
  LOST_PASSWORD: '/lost-password',
  HOME: '/',
  LOGIN: '/login',
  OLD_FORUM: '/old-forum',
  PHOTO: '/photo/:id',
  PHOTO_BATCH_UPLOAD_FOR_ALBUM: '/album/:id/multi-upload',
  PHOTO_EDIT: '/edit-photo',
  PHOTO_NEW: '/new-photo',
  PHOTO_NEW_FOR_ALBUM: '/album/:id/new-photo',
  PROFILE: '/profile',
  VIDEO: '/video/:id',
  VIDEO_EDIT: '/edit-video',
  VIDEO_NEW: '/new-video',
  VIDEO_NEW_FOR_ALBUM: '/album/:id/new-video',
  USER: '/rider/:id',
  USERS: '/riders',
};
export default routes;
